feat(tarball): add shasum from tarball when appropriate
zkat/pacote-old pull request #149
Opened 2018-04-17 12:42 UTC by imsnif

Heya!

This is the result some work done in relation to the discussion here: https://github.com/yarnpkg/yarn/issues/5654

When I started writing it, I thought this was an issue but then saw the tests specifically looking for that `null` value (mentioning: `// shasums are only when provided`). So I hope this is a wanted change! In my eyes it would be consistent with the rest of the behaviour. (I personally need this to facilitate lockfile conversion). But of course, if there's something I'm missing...

**Current Behavior:**
```javascript
pacote.manifest('ansi-regex@https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz')

// Manifest {
//  ...
//  _integrity: 'sha512-TIGnTpdo+...',
//  _shasum: null
// }
```

**After this PR:**
```javascript
pacote.manifest('ansi-regex@https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz')

// Manifest {
//  ...
//  _integrity: 'sha512-TIGnTpdo+...',
//  _shasum: 'c3b33ab5ee360d86e0e628f0468ae7ef27d654df'
// }
```

2018-04-17 17:08 UTC, zkat requested changes
You may want to add a similar exception for when the shasum is completely missing so we calculate it. See: https://github.com/zkat/pacote/blob/latest/lib/finalize-manifest.js#L143

2018-04-17 18:25 UTC, imsnif commented
@zkat - right! So I made the adjustment (and also adjusted some fixtures in the process).
I thought about optimizing this further by only requesting the relevant algorithms from `ssri.fromStream` here: https://github.com/zkat/pacote/pull/149/files#diff-d97a032389356a12ced608284b9c55edR156
I decided against it because I had the feeling it would mostly complicate the code. What do you think?

2018-04-18 17:33 UTC, zkat approved these changes
Tests seem to be passing pretty consistently now.

Why are node streams *so bad*?!

2018-04-18 17:35 UTC, zkat submitted a review, later dismissed
This mostly looks good! One tiny change left that I missed 👍

2018-04-18 17:35 UTC, zkat commented on lib/finalize-manifest.js
> +          _integrity: needsIntegrity && hash && hash.toString(),
This should probably be `hash.sha512.toString()`, since we don't currently put sha1s into the `integrity` field.

2018-04-18 18:49 UTC, zkat commented
Actually I'll just patch this myself real quick. This is good to merge in general. No need for more back-and-forth :)

2018-04-18 18:52 UTC, imsnif commented
@zkat - that's great! Just one more suggestion if I may: With your change, maybe we can toss this line? https://github.com/zkat/pacote/pull/149/files#diff-d97a032389356a12ced608284b9c55edR169

2018-04-18 18:52 UTC, zkat commented
oh! That's how you were doing it. I wondered why the tests were still passing. haha

2018-04-18 18:55 UTC, zkat commented
sorry for the rush -- didn't realize you were available and I just wanted to merge this, since I'm starting to put the release together. npm@6 is going out tomorrow :)

2018-04-18 18:56 UTC, imsnif commented
I actually just happened to walk in through the door. :)
On the contrary though - I very much appreciate the expedience!

2018-04-18 19:00 UTC, zkat commented
omg this is what I get for editing everything on github

2018-04-18 19:03 UTC, imsnif commented
Wait, doesn't everyone code like that?

2018-04-18 20:08 UTC, merged