Update deps
zkat/pacote-old pull request #165
Opened 2018-12-05 18:31 UTC by aeschright

Bringing everything up to date.

2018-12-05 18:35 UTC, zkat commented
Can you rebase and reword the various dependency updates to follow the commit message convention? This repo autogenerates changelogs and requires that commit messages look a certain way. Look through the git log for what other dep updates look like, and use `fix(test): ...` for the test fixup.

2018-12-05 18:36 UTC, zkat requested changes
Can you rebase and reword the various dependency updates to follow the commit message convention? This repo autogenerates changelogs and requires that commit messages look a certain way. Look through the git log for what other dep updates look like, and use fix(test): ... for the test fixup.

2018-12-06 21:25 UTC, aeschright commented
Updated everything, and the only remaining CI failure is the Windows jobs. I'm looking at their docs to see if there's an obvious fix.

2018-12-21 19:05 UTC, zkat approved these changes

2018-12-21 19:05 UTC, merged