Send certificate authority options
zkat/pacote-old pull request #95
Opened 2017-06-02 13:13 UTC by colinrotherham

Custom certificate config (e.g. via `npm config set cafile`) isn't making their way into `make-fetch-happen`, this appears to be an `npm@5` regression.

This pull ensures the option is passed from `npm` -> `pacote` -> `make-fetch-happen`.

See the discussion here: https://github.com/npm/npm/issues/16868

2017-06-02 17:17 UTC, zkat commented
Looking at https://github.com/zkat/make-fetch-happen/blob/latest/agent.js#L130-L135, it seems like I forgot a few other options. We should make sure we're passing in `strictSSL`, `key`, `certfile`, and `localAddress`. I also noticed `ca`, `key`, and `certfile` don't [get passed in to pacote](https://github.com/npm/npm/blob/release-next/lib/config/pacote.js#L18-L43) so a PR for that would be nice, too.

Could you add those other options here? And maybe do the npm PR, too?

2017-06-02 17:17 UTC, zkat requested changes
some other options are missing, and it'd be nice to have them in this PR

2017-06-03 20:02 UTC, colinrotherham commented
Hi @zkat,

Additional options added.

2017-06-03 23:42 UTC, zkat approved these changes

2017-06-03 23:43 UTC, merged